const URLS = {
    httpServer: import.meta.env.VITE_URL_SERVER,
    portServer: import.meta.env.VITE_PORT_SERVER,
    portClient: import.meta.env.VITE_PORT_CLIENT,
    saveChange: '/saveChange',
    getRooms: '/getRooms',
    createRoom: '/createRoom',
    disconnect: '/disconnect',
    update: 'update',
    connection: 'connection',
    joinNewRoom: 'joinNewRoom',
    joinExistingRoom: 'joinExistingRoom',
    newUsersArray: 'newUsersArray',
    newUserConnect: 'newUserConnect',
    auth: 'auth',
    room: '',
    clientValueСhanged: 'clientValueСhanged',
    serverValue: 'serverValue',
    positionCursorChange: 'positionCursorChange',
    serverCursors: 'serverCursors',
    clientDisconnect: 'clientDisconnect',
    positionTextCursorChange: 'positionTextCursorChange',
    serverTextCursors: 'serverTextCursors',
    languageChange: 'languageChange',
    serverLanguage: 'serverLanguage',
};
export default URLS;
